### ISSUE TITLE
For significant location change, if the user restart the device then it is not triggering the location based survey notifications.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#13]
**Scenario:**
1. Restart the device (to emulate a sudden unplanned restart on device).
After the device is turned on, the survey notifications are not getting triggered even if the user is in that location.

**Comment by dinesh-opg** [comment]
The issue is like when we restart the device the geofencing service is not started automatically.
So on boot completed we are checking that the service is already running beofore device shutdown and if already running before device shutdown we will start the service on device boot completed.This is handled using a broadcast reciever.
The issue is fixed

**Comment by onepointpb** [comment]
In the latest build the fix is working fine and verified.
