### ISSUE TITLE
Login to the app through Facebook is not working.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#20]
In both iOS and Android we are getting this issue.

**Comment by dinesh-opg** [comment]
We have added new debug and the signed hashkeys for facebook in the MySurveys app in the facebook developers account not it is working fine in android MySurveys app .

**Comment by dinesh-opg** [comment]
There is further issue this fb login is happening for some users only.We are getting 500 error from some users server.

**Comment by vivek-onepoint** [comment]
Hi,
While debugging the code i have found that facebook access token contains some information like user name, id and email address. Token given by dinesh which is not working is because in that email id is not there.

This issue can be because of email details are not updated properly in it.
May be they didn't allow to use email id (permission not given)
And also some time it fails to get details.

Better we should create a new account and try using that because other tokens are working fine with the same code.

**Comment by onepointpb** [comment]
With the newly created App ID it is working now. We have to monitor this for some more days.
