### ISSUE TITLE
Barcode scan is displaying blank results after scan for some items.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#32]
This occurred in case of XML content in the QR code.

**Comment by NeerajOPG** [comment]
The device is able to scan OR code with xml data  but its not displaying in the UI because we were using t.barcodeElm.html(n) to set the text value and we can not set the xml value to a element using "t.barcodeElm.html(n)". We have replace "t.barcodeElm.html(n)" with "t.barcodeElm.text(n)" now its working fine. We have updated the same in servers also.

**Comment by onepointpb** [comment]
Verified.
