### ISSUE TITLE
App issue: Unable to Upload Receipts

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#38]
There is an issue reported by one of our client with app survey(online). The project is such that they upload as many as receipts possible to gain rewards.
Qc tested the issue and has confirmed that they were able to replicate the issue.Please find the steps below:
1. Clicked Camera.
2. Took a picture. Then clicked on Save.
3. Then it re-loaded the survey question again. On clicking Upload Image it displayed an alert "No Image selected". 
4. But took a picture separately. Then uploaded by selecting the Gallery option and it worked. 

Device specification/configuration:
Device Model: Samsung Galaxy Fame S6810
Android OS Version - 4.1.2
RAM - 512 MB

**Comment by NeerajOPG** [comment]
We are not able to replicate the issue even the survey is not loading first time. 
we are getting "status=3" in the URL  for 1st question that's why SDK terminates the survey immediately.

Also we are able to take survey after modifying the script but some panellist are able to take survey with original script.
@dougmorris  has fixed similar kind of issue. 
https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-iOS/issues/5
