### ISSUE TITLE
Issue in getting the geofence surveys from the api 

### ISSUE THREAD

**Issue by dinesh-opg** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#61]
Issue in getting the list of Geofence Surveys from the api  "Geofencing/Geofencing"
getting error message.

{"ErrorMessage":"Object reference not set to an instance of an object.","HttpStatusCode":406,"Message":"An error has encountered."}

**Comment by vivek-onepoint** [comment]
Hi @dinesh-opg @onepointpb,

Issue is been fixed and updated. You can have a look and confirm.
Because of some changes made for polygon geofencing in api as well as in database was not updated in other servers (I guess its not finished for release in other servers). I have made some changes to staging server for this.

If you can confirm it works fine, i will compare and provide the api packages and db changes for Live.

**Comment by dinesh-opg** [comment]
Hi @vivek-onepoint 
 Tested in staging it is working fine ,you can move the changes to live.

**Comment by vivek-onepoint** [comment]
Hi,

API Changes have been moved to live.

**Comment by dinesh-opg** [comment]
Hi @vivek-onepoint
Tested in live it is working fine.
