### ISSUE TITLE
Staging: Geo location surveys are not working

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#69]
- When we create a location triggered survey, the notification is triggered after some time even if we haven't specified any delay(Exit/Enter) in the survey setup.
-After the notification is triggered, the survey isn't enabled (in Android)
-In iOS, Survey notification is triggered, when we click on take survey-> it throws an error asking us to choose the correct panel (correct panel was chosen). When we try taking the survey from 'By Location' tab-> it says you are not in the location.

Same is with the Live.

**Comment by nikul-opg** [comment]
I've checked the issue the problem is with mapquest. it's not picking up the right coordinated for the given address. If I add the address and coordinates manually then it's working fine.

**Comment by durgajadapolu** [comment]
I have checked this issue problem is geolocation survey ref is not matching with current panel survey ref. So it's showing an error to choose the correct panel.

**Comment by pavithra-opg** [comment]
@durgajadapolu @nikul-opg : so do we have to check anything more from our side or will it passed on to the backend team?

**Comment by durgajadapolu** [comment]
**Survey notification is triggered :** This is because your current location has geofencing survey so it got triggered. If you try to take that survey it throws an error asking us to choose the correct panel - Because this survey belongs to different panel.

**By Location tab :** Your selected panel contains geofencing survey of different location which is so far of your current location. So your are trying to take that survey by selecting location tab with selected survey in the list. It will says you are not in the location because your panel geofencing survey is not in your current location radius.

**Comment by pavithra-opg** [comment]
@durgajadapolu @nikul-opg 
Tested the geo-fencing surveys after adding the lat & long values manually in both Android and iOS, below are my findings:
- Android it works as intended
- iOS, before we sign in and select a panel, it throws error stating that the panel is wrong.
  Received survey notification for a survey which is expired(showed this to Durga)
  Push notification isn't working

**Comment by durgajadapolu** [comment]
**#iOS, before we sign in and select a panel, it throws error stating that the panel is wrong.**
- This one it is not reproducing every time, So I will check and let you know.

**#Received survey notification for a survey which is expired(showed this to Durga)**
- This is because currently we are not checking any validation for geofencing trigging notifications if it got expired. we are checking the present location has geofencing survey or not from the list of geofencing survey list if there it will trigger.  

**#Push notification isn't working**
- This one I am checking with vivek once it is done I will let you know.

**Comment by durgajadapolu** [comment]
#Push notification isn't working
- I have checked with vivek from service side notification are generated, but some time it throws error message device token is not correct and you won't get push notifications to device.

**Explanation :-** If one ID is login in one device notifications will work fine. One ID with multiple device eg : I have login in iOS device and I did't logout and again I have login in android here is the problem happens one Id has two device token so notifications won't work. It throw error message from service side.

**Test cases :** 
- If X user login in iOS device and logout and login in android device and logout, push 
   notifications will work fine.
- If X user login in iOS device and did't logout if we are forcefully uninstall the application(iOS) or 
  same X user login in android device and forcefully uninstall the application(android). Then Y 
  user login in same device it update same device token with multiple ID's(X&Y).
- So X user with multiple device token / Y user with multiple device token / X & Y has same 
  device token  in server DB so we won't get notification until new device token should updated in 
  server side old device token should be deleted / override when user login into the application.

We need to get a solution for this, then push notification will work.

**Comment by durgajadapolu** [comment]
Geofencing triggering surveys notifications are working fine I have checked in staging and live.
Push notification are working in staging pending to check in live because new certificate will be added in live server.

**Comment by pavithra-opg** [comment]
This issue is resolved.
